# Generated by Django 6.0 on 2025-12-26 20:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=250, populate_from='title', unique_with=('publish',)),
        ),
    ]
